// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_haversine
Rcpp::NumericMatrix rcpp_haversine(Rcpp::NumericMatrix x);
RcppExport SEXP _geodist_rcpp_haversine(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_haversine(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_haversine_xy
Rcpp::NumericMatrix rcpp_haversine_xy(Rcpp::NumericMatrix x, Rcpp::NumericMatrix y);
RcppExport SEXP _geodist_rcpp_haversine_xy(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_haversine_xy(x, y));
    return rcpp_result_gen;
END_RCPP
}
