# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' haversine
#'
#' Haversine for variable x and y
#'
#' @return single distance
#'
#' @noRd
NULL

#' rcpp_haversine
#'
#' @return single distance
#'
#' @noRd
rcpp_haversine <- function(x) {
    .Call(`_geodist_rcpp_haversine`, x)
}

#' rcpp_haversine
#'
#' @return single distance
#'
#' @noRd
rcpp_haversine_xy <- function(x, y) {
    .Call(`_geodist_rcpp_haversine_xy`, x, y)
}

