# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_haversine
#'
#' @return single distance
#'
#' @noRd
rcpp_haversine <- function(x1, y1, x2, y2) {
    .Call(`_geodist_rcpp_haversine`, x1, y1, x2, y2)
}

